[package]
name = "psacak"
version = "0.0.1"
edition = "2018"

[dependencies]
libc = "0.2"
term-table = "1.2"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"

[profile.release]
debug = true
