[package]
name = "psacak"
version = "0.0.2"
edition = "2018"

[dependencies]
libc = "0.2"
term-table = "1.2"
rayon = "1.3"
crossbeam = "0.7"
scoped_threadpool = "0.1"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"

[profile.release]
debug = true
